export default `ltm pool Common/always_down-pool {
    active-member-cnt 1
    available-member-cnt 1
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 0
    monitor-rule Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/always_down-pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state available
    status.enabled-state enabled
    status.status-reason The pool is available
    tot-requests 0
}
ltm pool Common/always_down_02-pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 0
    monitor-rule Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/always_down_02-pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Common/bigipreport {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 0
    monitor-rule Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/bigipreport
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Common/ipv6pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 0
    monitor-rule Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/ipv6pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Common/loadbalancing-se {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 0
    monitor-rule Common/loadbalancing-se-https
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/loadbalancing-se
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Common/mc-hoga_pool {
    active-member-cnt 1
    available-member-cnt 1
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 0
    monitor-rule Common/udp
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/mc-hoga_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state available
    status.enabled-state enabled
    status.status-reason The pool is available
    tot-requests 0
}
ltm pool Sample_http_01/A1/web_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_01/A1/web_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_02/A1/dfl_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_02/A1/dfl_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_02/A1/pvt_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_02/A1/pvt_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_03/A1/web_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_03/A1/web_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_07/A1/web_pool80 {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/web_pool80
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_07/A1/web_pool81 {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/web_pool81
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_07/A1/web_pool82 {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/web_pool82
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool Sample_http_08/A1/web_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 2
    min-active-members 1
    monitor-rule min 1 of /Common/http
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_08/A1/web_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}
ltm pool example_NAT64/App1/web_pool {
    active-member-cnt 0
    available-member-cnt 0
    connq-all.age-edm 0
    connq-all.age-ema 0
    connq-all.age-head 0
    connq-all.age-max 0
    connq-all.depth 0
    connq-all.serviced 0
    connq.age-edm 0
    connq.age-ema 0
    connq.age-head 0
    connq.age-max 0
    connq.depth 0
    connq.serviced 0
    cur-priogrp 0
    cur-sessions 0
    highest-priogrp 0
    lowest-priogrp 0
    member-cnt 1
    min-active-members 1
    monitor-rule min 1 of /example_NAT64/App1/grafana_http_monitor
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name example_NAT64/App1/web_pool
    serverside.bits-in 0
    serverside.bits-out 0
    serverside.cur-conns 0
    serverside.max-conns 0
    serverside.pkts-in 0
    serverside.pkts-out 0
    serverside.tot-conns 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    tot-requests 0
}`;