const vipExampleData = `ltm virtual Common/bigipreport {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 192.168.70.248:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/bigipreport
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/forwardasd {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination any:any
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/forwardasd
    one-min-avg-usage-ratio 0
    status.availability-state unknown
    status.enabled-state enabled
    status.status-reason The children pool member(s) either don't have service checking enabled, or service check results are not available yet
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/loadbalancing.se {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.10.10.1:443
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/loadbalancing.se
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/mc-hoga {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 192.168.70.244:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/mc-hoga
    one-min-avg-usage-ratio 0
    status.availability-state unknown
    status.enabled-state enabled
    status.status-reason The children pool member(s) either don't have service checking enabled, or service check results are not available yet
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/poolstatus {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 192.168.70.247:443
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/poolstatus
    one-min-avg-usage-ratio 0
    status.availability-state unknown
    status.enabled-state enabled
    status.status-reason The children pool member(s) either don't have service checking enabled, or service check results are not available yet
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/select-pool-by-irule {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.10.10.2:443
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/select-pool-by-irule
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Common/working {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 192.168.70.246:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Common/working
    one-min-avg-usage-ratio 0
    status.availability-state unknown
    status.enabled-state enabled
    status.status-reason The children pool member(s) either don't have service checking enabled, or service check results are not available yet
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_01/A1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.0.6.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_01/A1/service
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_02/A1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.0.3.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_02/A1/service
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_03/A1/pvt_vs {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.1.7.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_03/A1/pvt_vs
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_03/A1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.0.7.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_03/A1/service
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_07/A1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.1.10.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/service
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_07/A1/service_on_port81 {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.1.10.10:81
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/service_on_port81
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_07/A1/service_on_port82 {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.1.10.10:82
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_07/A1/service_on_port82
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual Sample_http_08/A1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 10.0.1.10:80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name Sample_http_08/A1/service
    one-min-avg-usage-ratio 0
    status.availability-state unknown
    status.enabled-state enabled
    status.status-reason The children pool member(s) either don't have service checking enabled, or service check results are not available yet
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}
ltm virtual example_NAT64/App1/service {
    clientside.bits-in 0
    clientside.bits-out 0
    clientside.cur-conns 0
    clientside.evicted-conns 0
    clientside.max-conns 0
    clientside.pkts-in 0
    clientside.pkts-out 0
    clientside.slow-killed 0
    clientside.tot-conns 0
    cmp-enable-mode all-cpus
    cmp-enabled enabled
    cs-max-conn-dur 0
    cs-mean-conn-dur 0
    cs-min-conn-dur 0
    destination 9161:7904:7539:6023:5c73:2b27:50c6:46ce.80
    ephemeral.bits-in 0
    ephemeral.bits-out 0
    ephemeral.cur-conns 0
    ephemeral.evicted-conns 0
    ephemeral.max-conns 0
    ephemeral.pkts-in 0
    ephemeral.pkts-out 0
    ephemeral.slow-killed 0
    ephemeral.tot-conns 0
    five-min-avg-usage-ratio 0
    five-sec-avg-usage-ratio 0
    mr.msg-in 0
    mr.msg-out 0
    mr.req-in 0
    mr.req-out 0
    mr.resp-in 0
    mr.resp-out 0
    name example_NAT64/App1/service
    one-min-avg-usage-ratio 0
    status.availability-state offline
    status.enabled-state enabled
    status.status-reason The children pool member(s) are down
    syncookie-status not-activated
    syncookie.accepts 0
    syncookie.hw-accepts 0
    syncookie.hw-syncookies 0
    syncookie.hwsyncookie-instance 0
    syncookie.rejects 0
    syncookie.swsyncookie-instance 0
    syncookie.syncache-curr 0
    syncookie.syncache-over 0
    syncookie.syncookies 0
    tot-requests 0
}`

export default vipExampleData;